<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Activity;

class ActivitySeeder extends Seeder
{
    public function run(): void
    {
        $companyCodes = ['COO1', 'COO2', 'COO3', 'COO4', 'COO5'];

        $activities = [
            [
                'title' => 'Community Beach Cleanup Drive',
                'description' => 'Join volunteers to clean the shoreline, sort waste for recycling, and run awareness activities about marine conservation.',
                'start_date' => '2025-07-05',
                'end_date' => '2025-07-05',
                'category' => 'Lingkungan',
                'location' => 'Pantai Indah',
                'quota' => 50,
            ],
            [
                'title' => 'After-School Tutoring for Underprivileged Kids',
                'description' => 'Volunteer tutors needed to help children with basic literacy, numeracy, and study skills in after-school sessions.',
                'start_date' => '2025-08-01',
                'end_date' => '2025-08-30',
                'category' => 'Pendidikan',
                'location' => 'Pusat Komunitas Utama',
                'quota' => 40,
            ],
            [
                'title' => 'Senior Care Visit & Conversation',
                'description' => 'Spend time with seniors in the community home: conversation, light activities, and companionship for elderly residents.',
                'start_date' => '2025-09-10',
                'end_date' => '2025-09-10',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Panti Wredha Harapan',
                'quota' => 50,
            ],
            [
                'title' => 'Urban Tree Planting Weekend',
                'description' => 'Help plant native trees in urban parks, assist with tree guards, and learn about urban reforestation benefits.',
                'start_date' => '2025-10-18',
                'end_date' => '2025-10-19',
                'category' => 'Lingkungan',
                'location' => 'Taman Kota',
                'quota' => 50,
            ],
            [
                'title' => 'Mobile Health Clinic Support',
                'description' => 'Assist medical teams by helping with patient registration, crowd guidance, and basic logistics at the mobile clinic.',
                'start_date' => '2025-11-02',
                'end_date' => '2025-11-02',
                'category' => 'Kesehatan',
                'location' => 'Lapangan Serbaguna',
                'quota' => 50,
            ],
            [
                'title' => 'Literacy Campaign: Book Donation & Reading',
                'description' => 'Collect and distribute books to community libraries; volunteers will also read aloud in children sessions.',
                'start_date' => '2025-12-01',
                'end_date' => '2025-12-03',
                'category' => 'Pendidikan',
                'location' => 'Perpustakaan Sekitar',
                'quota' => 50,
            ],
            [
                'title' => 'Youth Leadership Workshop Facilitation',
                'description' => 'Facilitators needed to run soft-skill workshops for youth: public speaking, teamwork, and project planning.',
                'start_date' => '2025-12-10',
                'end_date' => '2025-12-11',
                'category' => 'Pengembangan Anak Muda',
                'location' => 'Aula Serbaguna',
                'quota' => 50,
            ],
            [
                'title' => 'Food Drive & Distribution for Families in Need',
                'description' => 'Organize, pack, and distribute food parcels to vulnerable families in the neighborhood.',
                'start_date' => '2025-12-20',
                'end_date' => '2025-12-20',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Gereja & Pusat Komunitas',
                'quota' => 50,
            ],
            [
                'title' => 'Disaster Preparedness Community Training',
                'description' => 'Volunteer trainers to teach disaster preparedness, basic first aid, and evacuation planning to local communities.',
                'start_date' => '2026-01-15',
                'end_date' => '2026-01-16',
                'category' => 'Kesiapsiagaan',
                'location' => 'Balai Desa',
                'quota' => 50,
            ],
            [
                'title' => 'Recycling Workshop for Schools',
                'description' => 'Hands-on workshop teaching students how to recycle and upcycle waste into useful items.',
                'start_date' => '2026-02-05',
                'end_date' => '2026-02-05',
                'category' => 'Lingkungan',
                'location' => 'Sekolah Dasar Negeri 3',
                'quota' => 50,
            ],
            [
                'title' => 'Community Mural Painting Project',
                'description' => 'Artists and helpers collaborate with youth to paint murals that reflect community identity and hope.',
                'start_date' => '2026-03-10',
                'end_date' => '2026-03-12',
                'category' => 'Seni dan Budaya',
                'location' => 'Gang Seni',
                'quota' => 50,
            ],
            [
                'title' => 'Skills Bootcamp: Basic Computer for Jobseekers',
                'description' => 'Teach essential computer and internet skills to jobseekers to improve employment opportunities.',
                'start_date' => '2026-03-25',
                'end_date' => '2026-03-27',
                'category' => 'Pengembangan Anak Muda',
                'location' => 'Kantor Komunitas',
                'quota' => 50,
            ],
            [
                'title' => 'Community Health Awareness Campaign',
                'description' => 'Volunteers help run booths, distribute flyers, and educate about hygiene, nutrition, and prevention.',
                'start_date' => '2026-04-07',
                'end_date' => '2026-04-07',
                'category' => 'Kesehatan',
                'location' => 'Alun-alun Kota',
                'quota' => 50,
            ],
            [
                'title' => 'Accessible Playground Build',
                'description' => 'Join a team to build inclusive playground features for children with disabilities.',
                'start_date' => '2026-04-20',
                'end_date' => '2026-04-22',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Taman Anak',
                'quota' => 50,
            ],
            [
                'title' => 'Coastal Wildlife Monitoring Patrol',
                'description' => 'Assist environmentalists in simple monitoring tasks to track coastal wildlife and plastic hotspots.',
                'start_date' => '2026-05-05',
                'end_date' => '2026-05-06',
                'category' => 'Lingkungan',
                'location' => 'Pesisir Selatan',
                'quota' => 50,
            ],
            [
                'title' => 'Career Mentoring for High School Seniors',
                'description' => 'Mentors provide guidance on higher education, vocational routes, and job application tips.',
                'start_date' => '2026-05-20',
                'end_date' => '2026-05-20',
                'category' => 'Pendidikan',
                'location' => 'SMAN 1',
                'quota' => 50,
            ],
            [
                'title' => 'Community Sports Day & Volunteer Marshals',
                'description' => 'Organize community sports activities; volunteers act as marshals, referees, and coordinators.',
                'start_date' => '2026-06-08',
                'end_date' => '2026-06-08',
                'category' => 'Kegiatan Komunitas',
                'location' => 'Lapangan Bola',
                'quota' => 50,
            ],
            [
                'title' => 'Neighborhood Home Repairs for Elderly',
                'description' => 'Volunteer builders help with small home repairs and safety improvements for elderly residents.',
                'start_date' => '2026-06-18',
                'end_date' => '2026-06-19',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Komunitas RW 07',
                'quota' => 50,
            ],
            [
                'title' => 'Youth Environmental Film Screening',
                'description' => 'Screen films about environment and sustainability followed by discussion sessions led by volunteers.',
                'start_date' => '2026-07-02',
                'end_date' => '2026-07-02',
                'category' => 'Seni dan Budaya',
                'location' => 'Gedung Serba Guna',
                'quota' => 50,
            ],
            [
                'title' => 'Skills Exchange: Sewing & Crafting for Income',
                'description' => 'Train community members in sewing and crafting to help generate small-scale income opportunities.',
                'start_date' => '2026-07-15',
                'end_date' => '2026-07-17',
                'category' => 'Pengembangan Komunitas',
                'location' => 'Ruang Kegiatan Lokal',
                'quota' => 50,
            ],
            [
                'title' => 'Community Food Sharing Program',
                'description' => 'Support food distribution and coordination for families during year-end season.',
                'start_date' => '2025-11-15',
                'end_date' => '2026-01-15',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Balai Warga',
                'quota' => 50,
            ],
            [
                'title' => 'Learning Support for Elementary Students',
                'description' => 'Assist children with homework and basic learning activities after school.',
                'start_date' => '2025-11-10',
                'end_date' => '2026-01-20',
                'category' => 'Pendidikan',
                'location' => 'Pusat Belajar',
                'quota' => 50,
            ],
            [
                'title' => 'Public Park Care Initiative',
                'description' => 'Help maintain cleanliness and facilities in public parks.',
                'start_date' => '2025-11-01',
                'end_date' => '2026-02-01',
                'category' => 'Lingkungan',
                'location' => 'Taman Kota',
                'quota' => 50,
            ],
            [
                'title' => 'Community Health Assistance Program',
                'description' => 'Support registration and basic assistance during community health services.',
                'start_date' => '2025-11-20',
                'end_date' => '2026-01-31',
                'category' => 'Kesehatan',
                'location' => 'Puskesmas',
                'quota' => 50,
            ],
            [
                'title' => 'Youth Skill Development Sessions',
                'description' => 'Support mentoring and skill-building activities for local youth.',
                'start_date' => '2025-11-18',
                'end_date' => '2026-02-10',
                'category' => 'Pengembangan Anak Muda',
                'location' => 'Ruang Kreatif',
                'quota' => 50,
            ],
            [
                'title' => 'Elderly Companion & Support Visits',
                'description' => 'Provide companionship and light assistance to elderly residents.',
                'start_date' => '2025-11-05',
                'end_date' => '2026-01-25',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Panti Wredha',
                'quota' => 50,
            ],
            [
                'title' => 'Neighborhood Waste Sorting Initiative',
                'description' => 'Assist households with waste separation and recycling routines.',
                'start_date' => '2025-11-12',
                'end_date' => '2026-02-05',
                'category' => 'Lingkungan',
                'location' => 'TPS Terpadu',
                'quota' => 50,
            ],
            [
                'title' => 'Community Disaster Readiness Program',
                'description' => 'Help residents prepare emergency kits and evacuation plans.',
                'start_date' => '2025-11-22',
                'end_date' => '2026-01-22',
                'category' => 'Kesiapsiagaan',
                'location' => 'Balai Desa',
                'quota' => 50,
            ],
            [
                'title' => 'School Meal Support Activities',
                'description' => 'Assist in meal preparation and distribution for students.',
                'start_date' => '2025-11-08',
                'end_date' => '2026-01-18',
                'category' => 'Pendidikan',
                'location' => 'Sekolah Negeri',
                'quota' => 50,
            ],
            [
                'title' => 'Community Art & Creative Workshops',
                'description' => 'Support art workshops and creative sessions for residents.',
                'start_date' => '2025-11-14',
                'end_date' => '2026-02-01',
                'category' => 'Seni dan Budaya',
                'location' => 'Ruang Seni',
                'quota' => 50,
            ],
            [
                'title' => 'Digital Skills Support for Jobseekers',
                'description' => 'Assist jobseekers with basic computer skills and online applications.',
                'start_date' => '2025-11-25',
                'end_date' => '2026-02-15',
                'category' => 'Pengembangan Anak Muda',
                'location' => 'Lab Komputer',
                'quota' => 50,
            ],
            [
                'title' => 'Community Recycling Education Program',
                'description' => 'Help educate residents on recycling practices and routines.',
                'start_date' => '2025-11-03',
                'end_date' => '2026-01-30',
                'category' => 'Lingkungan',
                'location' => 'Bank Sampah',
                'quota' => 50,
            ],
            [
                'title' => 'Local Sports & Fitness Activities',
                'description' => 'Assist with organizing regular sports and fitness activities.',
                'start_date' => '2025-11-17',
                'end_date' => '2026-01-17',
                'category' => 'Kegiatan Komunitas',
                'location' => 'Lapangan Olahraga',
                'quota' => 50,
            ],
            [
                'title' => 'Home Safety Improvement for Seniors',
                'description' => 'Support light home repairs and safety improvements for elderly households.',
                'start_date' => '2025-11-09',
                'end_date' => '2026-02-09',
                'category' => 'Kesejahteraan Sosial',
                'location' => 'Lingkungan RW',
                'quota' => 50,
            ],
            [
                'title' => 'Children Reading Corner Program',
                'description' => 'Assist daily reading and literacy activities for children.',
                'start_date' => '2025-11-28',
                'end_date' => '2026-01-28',
                'category' => 'Pendidikan',
                'location' => 'Perpustakaan Komunitas',
                'quota' => 50,
            ],
        ];

        foreach ($activities as $act) {
            // ambil kata pertama dari title
            $firstWord = explode(' ', trim($act['title']))[0] ?? 'default';

            // sanitize: hanya huruf/angka/dash, lowercase
            $cleanFirst = preg_replace('/[^a-z0-9\-]/', '', strtolower($firstWord));

            // bentuk image_url
            $imageUrl = 'img/' . ($cleanFirst ?: 'default') . '.jpg';

            Activity::factory()->create([
                'title' => $act['title'],
                'description' => $act['description'],
                'image_url' => $imageUrl,
                'start_date' => $act['start_date'],
                'end_date' => $act['end_date'],
                'category' => $act['category'],
                'location' => $act['location'] ?? null,
                'quota' => $act['quota'],
                // company_code random dari COO1..COO5
                'company_code' => $companyCodes[array_rand($companyCodes)],
            ]);
        }
    }
}
